const footer = [
  'Meals',
  'A fresh and modern theme for all charity',
  'Contact Us',
  '123 Liverpool Street United Kingdom-1205',
  'Useful Links',
  'Home',
  'About Us',
  'Our Causes',
  'Our Events',
  'Contact',
  'Our Causes',
  'Water Purify',
  'Food Collect',
  'Food Collect',
  'Food Collect',
  'Food Collect',
  'Subscribe',
  'Charry is a nonproﬁt',
  'Charry is a nonproﬁt',
  'Charry is a nonproﬁt',
];
module.exports = footer;
